name: avoiding_bubbles
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.9.30
  - certifi=2021.10.8
  - cffi=1.14.6
  - cycler=0.10.0
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gettext=0.21.0
  - glib=2.69.1
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.3
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.8.12
  - python-dateutil=2.8.2
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2020.3
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - charset-normalizer==2.0.7
    - idna==3.3
    - lppls==0.6.1
    - lxml==4.6.3
    - multitasking==0.0.9
    - pandas==1.3.3
    - pytz==2021.3
    - requests==2.26.0
    - urllib3==1.26.7
    - yfinance==0.1.63